# Generated by Django 4.2.7 on 2023-11-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompra',
            name='videojuego',
            field=models.CharField(max_length=5000),
        ),
    ]
