# Generated by Django 4.2.7 on 2023-11-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_historialcompra_videojuego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompra',
            name='videojuego',
            field=models.CharField(max_length=50),
        ),
    ]
