# Generated by Django 5.0 on 2024-07-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
        ('inventory', '0002_videogame_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='comments',
            field=models.ManyToManyField(blank=True, to='blog.comment'),
        ),
    ]
